# Generated by Django 5.0.3 on 2024-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_Admin',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('mobile', models.CharField(max_length=100, verbose_name='Mobile')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=100, verbose_name='Confirm Password')),
            ],
        ),
    ]
