# Generated by Django 5.0.3 on 2024-04-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
