# Generated by Django 5.0.3 on 2024-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('unique_id', models.CharField(max_length=100, unique=True, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mobile_number', models.CharField(max_length=100, verbose_name='Mobile Number')),
            ],
        ),
    ]
