# Generated by Django 5.0.3 on 2024-04-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_enduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='username',
        ),
    ]
