# Generated by Django 5.0.3 on 2024-04-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_enduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll_Admin',
        ),
    ]
