# Generated by Django 5.0.3 on 2024-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polladmin',
            name='mobile',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
