# Generated by Django 5.0.3 on 2024-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0004_alter_polladmin_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polladmin',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
