# Generated by Django 5.0.3 on 2024-04-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0007_remove_vote_poll_delete_poll_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polladmin',
            name='id',
        ),
        migrations.AddField(
            model_name='polladmin',
            name='confirm_password',
            field=models.CharField(default='', max_length=100, verbose_name='Confirm Password'),
        ),
        migrations.AddField(
            model_name='polladmin',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polladmin',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='polladmin',
            name='mobile',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='polladmin',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='polladmin',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
