# Generated by Django 5.0.3 on 2024-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0009_alter_polladmin_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='Unique ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
            ],
        ),
    ]
